import './js/color-switcher';
import './js/getRecentUploads';
import './js/searchAnime';
import './js/getTopAnime';
import './js/popup'
import './js/addAnimeStorage';
import './js/renderStorage';
import './js/dislikeAnimeFromLibrary';
import './js/functions/apiQuote';
import './js/renderQuotes';